# Mapping of symlinks.
#
# Notes:
#     __root__ will be replaced by user root directory.
#

# All non-standard directories, to create if doesn't exist.
directories:
    - __root__.pip
    - __root__.tmux/plugins
    - __root__.vim/autoload
    - __root__.antigen
    - __root__.config/alacritty

# List of all symlinks.
links:
    __root__.vimrc:                            vim/vimrc
    __root__.vim/plugins.vim:                  vim/plugins.vim
    __root__.vim/general.vim:                  vim/general.vim
    __root__.vim/theme.vim:                    vim/theme.vim
    __root__.vim/keybindings.vim:              vim/keybindings.vim
    __root__.vim/functions.vim:                vim/functions.vim
    __root__.vim/autoload/plug.vim:            vim/autoload/plug.vim
    __root__.aliases:                          zsh/aliases
    __root__.functions:                        zsh/functions
    __root__.prompt:                           zsh/prompt
    __root__.antigen/antigen.zsh:              zsh/antigen.zsh
    __root__.zshrc:                            zsh/zshrc
    __root__.tmux.conf:                        tmux/tmux.conf
    __root__.chunkwmrc:                        chunkwm/chunkwmrc
    __root__.gitconfig:                        git/gitconfig
    __root__.gitignore_global:                 git/gitignore_global
    __root__.config/alacritty/alacritty.yml:   alacritty/alacritty.yml
    __root__.pip/pip.conf:                     pip/pip.conf
    __root__.tmux/plugins/tmux-battery:        tmux/plugins/tmux-battery
    __root__.tmux/plugins/tmux-cpu:            tmux/plugins/tmux-cpu
    __root__.tmux/plugins/tmux-sensible:       tmux/plugins/tmux-sensible
    __root__.tmux/plugins/tpm:                 tmux/plugins/tpm
    /usr/local/bin/sketch:                     bin/sketch
    /usr/local/bin/pyzip:                      bin/pyzip
    /usr/local/bin/tubestatus:                 bin/tubestatus
    /usr/local/bin/256colors:                  bin/256colors

# Brew packages.
brew:
    - tmux
    - redis
    - nnn
    - lazygit
    - lazydocker
    - git
    - python3
    - ddgr
    - wget
    - zsh
    - mysql
    - sqlite
    - fzf
    - htop
    - exa
    - curl
    - bash
    - gnu-sed
    - tree
    - jsonnet
    - chunkwm
    - xclip
    - jq
    - fd
    - vim     # vim needs to be before macvim
    - macvim  # macvim needs to be after vim

# Brew cask installs.
cask:
    - sequel-pro
    - docker
    - alacritty
    - slack
    - alfred
    - ngrok
    - firefox
    - fontforge
